require('pcho.packer')
require('pcho.set')
require('pcho.utils')
require('pcho.colors')
require('pcho.keymap')

require('pcho.plugins.gitsigns')
require('pcho.plugins.lualine')
require('pcho.plugins.treesitter')
require('pcho.plugins.telescope')
require('pcho.plugins.lsp')
require('pcho.plugins.fugitive')

require('Comment').setup()
require('indent_blankline').setup()
